---
title: "Combine spatial measures to feed to model"
output: html_document
date: "2024-12-11"
---

# Summary

Here we combine the data created in the previous folders (01 and 03) so that we can feed it into a prediction model. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(qs)
library(here)
library(glue)

source(here("R/dir.R"))
grid <- read.csv(here("data/model_features/deg_1_x_1/global_grid.csv"))

```

```{r}
elnino <- read.csv(here("data/model_features/enso_index.csv"))

## read in Rousseau country level effort with gears that match to GFW data 
rousseau_eff <- qs::qread(here("data/int/rousseau_gear_fix.qs")) %>%
    group_by(year, flag_fin = country, gear = gear_new, length_category) %>%
    summarize(
      total_fishing_hours = sum(eff_active_hours, na.rm = TRUE),
      .groups = 'drop'
    )

years <- 2015:2017
model_data <- list()

for(yr in years) {
  # yr = 2015
  # Load effort proportions
  effort_props <- qread(file.path(rdsi_dir, glue("prep/gfw_props/deg_one/all_effort_gear_length_props_{yr}.qs"))) %>%
    mutate(year = yr) %>%
    filter(fishing_hours > 0)
  
  # Calculate total effort for each combination
  total_efforts <- rousseau_eff %>%
        filter(year == yr)
  

  
  # Combine all data
  year_data <- effort_props %>%
    mutate(sector = "I") %>% 
    # Add total effort for each combination
    left_join(total_efforts, by = c("flag_fin", "year", "gear", "length_category")) %>% # there are gaps here.. e.g., CHN doesn't have any vessels >50m in the Rousseau data, but does in GFW data - I actually don't think this matters though since we are predicting within the grouping represented in the Rousseau data. There might be issues with classifications in the Rousseau data but not in GFW?
    dplyr::select(
      # Response
      prop_fishing_hours_cell,
      lon = x, 
      lat = y,
      # Categorical predictors
      flag_fin, gear, length_category,
      
      # Total effort predictor
      total_fishing_hours,
      
      # Additional info
      year
    )
  
  model_data[[as.character(yr)]] <- year_data
}

# Combine all years
final_data <- bind_rows(model_data)

# Log transform total fishing hours PREDICTOR (since it might have a large range)
final_data$log_total_fishing_hours <- log1p(final_data$total_fishing_hours)


# Save prepared data
saveRDS(final_data, here("data/model_features/prepared_data_1deg.rds"))

```

