---
title: "Prep gfw fishing effort to feed to model for 0.5 degree"
output: html_document
date: "2024-12-11"
---

# Summary

Here we combine the data created in the previous folders (01 and 03) so that we can feed it into a prediction model. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(qs)
library(here)
library(glue)

source(here("R/dir.R"))
grid <- read.csv(here("data/model_features/global_grid.csv"))

```

```{r}

# # Function to load and process environmental data
# process_env_data <- function(year) {
#   
#   # year = 2015
#   # Load chlorophyll data
#   chl <- read.csv(here("data/model_features/erdMH1chlamday/errdap_2013_2017.csv")) %>% # since we're only training on 2015-2017
#     filter(year == !!year) %>%
#     dplyr::select(pixel_id, chl_mg_per_m3_mean, chl_mg_per_m3_sd)
#   
#   # Load SST data
#   if(year == 2015){ 
#   sst <- read.csv(here("data/model_features/ncdcOisst21Agg_LonPM180/errdap_sst_2011_2015.csv")) %>%
#     filter(year == !!year) %>%
#     dplyr::select(pixel_id, sst_c_mean, sst_c_sd)
#   
#   }else{
#       sst <- read.csv(here("data/model_features/ncdcOisst21Agg_LonPM180/errdap_sst_2016_2020.csv")) %>%
#     filter(year == !!year) %>%
#     dplyr::select(pixel_id, sst_c_mean, sst_c_sd)
#   }
#   
#   # Load wind data
#   wind <- read.csv(here("data/model_features/remss_wind/wind_2013_2017.csv")) %>%
#     filter(year == !!year) %>%
#     dplyr::select(pixel_id, wind_speed_mean = wind_speed_ms_mean, wind_speed_sd = wind_speed_ms_sd)
#   
#   # Join all environmental data
#   env_data <- chl %>%
#     left_join(sst, by = "pixel_id") %>%
#     left_join(wind, by = "pixel_id")
#   
#   return(env_data)
# }

# Load static spatial data
# spatial_data <- read.csv(here("data/model_features/gfw_static_spatial_measures.csv")) %>%
#   dplyr::select(pixel_id, lon, lat, elevation_m, distance_from_port_m, distance_from_shore_m)

# Load mesopelagic zone data
# meso_data <- read.csv(here("data/model_features/mesopelagic_zones.csv")) %>%
#   dplyr::select(pixel_id, meso_region) 

# # Load EEZ and FAO region data
# eez_data <- read.csv(here("data/model_features/eez/eez.csv")) %>%
#   filter(!is.na(pixel_id)) %>%
#   distinct()
# 
# fao_data <- read.csv(here("data/model_features/fao/fao.csv")) %>%
#   filter(!is.na(pixel_id)) %>%
#   distinct()

# Process each year
years <- 2015:2024
model_data <- list()

for(yr in years) {
  # yr = 2015
  # Load effort proportions
  effort_props <- qread(file.path(rdsi_dir, glue("prep/gfw_props/deg_half/all_effort_gear_length_props_{yr}.qs"))) %>%
    mutate(year = yr) %>% # fix this, an artifact of the way i saved the data before
    filter(fishing_hours > 0)

  
  # Load and process environmental data
  # env_data <- process_env_data(yr)
  
  # Combine all data
  year_data <- effort_props %>%
    mutate(sector = "I") %>% 
    # Add total effort for each combination
    # left_join(spatial_data, by = c("x" = "lon", "y" = "lat")) %>% # why are there some NAs for the spatial data? Land values in GFW. Need to figure out how to deal with this. 
    # left_join(env_data, by = "pixel_id") %>%
    # Add categorical spatial variables
   #  left_join(distinct(meso_data), by = "pixel_id") %>% # some duplicating happening here? Ignoring for now, because we need to fix this in the previous folder scripts. 
    # left_join(eez_data, by = "pixel_id") %>%
    # left_join(fao_data, by = "pixel_id") %>%
    dplyr::select(
      # Response
      prop_fishing_hours_cell,
      # Categorical predictors
      flag_fin, gear, length_category,
     # # meso_region, 
     #  eez_id, fao_id,
      # # Continuous predictors
      # lon = x, lat = y,
      # elevation_m,
      # distance_from_port_m,
      # distance_from_shore_m,
      # chl_mg_per_m3_mean,
      # chl_mg_per_m3_sd,
      # sst_c_mean,
      # sst_c_sd,
      # wind_speed_mean,
      # wind_speed_sd,
      # Additional info
      year
    )
  
  model_data[[as.character(yr)]] <- year_data
}

# Combine all years
final_data <- bind_rows(model_data)

# Save prepared data
saveRDS(final_data, here("data/model_features/prepared_data_0.5.rds"))

```

